name: setaksetikmobile
description: "An app for Steak Lovers, curated by C09."

publish_to: 'none'
version: 2.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  quiver: ^3.2.1
  http: ^1.2.2
  provider: ^6.1.2
  pbp_django_auth: ^0.4.0
  curved_navigation_bar: ^1.0.6
  intl: ^0.20.1
  flutter_fortune_wheel: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  effective_dart: ^1.3.2

flutter_icons:
  android: true
  image_path: "assets/images/setaksetik-icon.png"
  adaptive_icon_foreground: "assets/images/setaksetik-icon-foreground.png"
  adaptive_icon_background: "#F5F5DC"

flutter:
  uses-material-design: true

  assets:
      - assets/fonts/
      - assets/images/

  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
        - asset: assets/fonts/PlayfairDisplay-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-SemiBoldItalic.ttf
          style: italic
          weight: 600
